version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=dev
    restart: always  